services:
  db:
    image: postgres:18
    container_name: pc_club_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pc_club
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./db:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:

