# Generated by Django 5.2.13 on 2026-04-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'clubs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('model', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peripherals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.club')),
            ],
            options={
                'db_table': 'admins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClubPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.club')),
            ],
            options={
                'db_table': 'club_photos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('processor', models.TextField(blank=True, null=True)),
                ('gpu', models.TextField(blank=True, null=True)),
                ('ram', models.TextField(blank=True, null=True)),
                ('monitor_model', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
            ],
            options={
                'db_table': 'pcs',
                'managed': True,
                'unique_together': {('club', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=12)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
            ],
            options={
                'db_table': 'tariffs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.TextField(default='created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PcPeripheral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pc')),
                ('peripheral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.peripheral')),
            ],
            options={
                'db_table': 'pc_peripherals',
                'managed': True,
                'unique_together': {('pc', 'peripheral')},
            },
        ),
    ]
